### ISSUE TITLE
Template placer datapack does not work on 24w33a due to "functions" folder instead of "function" folder

### ISSUE THREAD

**Issue by Tisawesomeness** [misode/template-placer#3] opened 2024-08-15 16:18 UTC
The template placer datapack for 24w33a has the `data/minecraft/tags/functions` and `data/structure_placer/functions` directories. These should be `function` instead.

**Comment by misode** [comment] 2024-08-15 16:26
Duplicate of #2

**Closed as not planned by misode** 2024-08-15 16:26 UTC
Labels: duplicate
